site_name: Hacker Notebook
site_url: https://hackernotebook.com
theme:
  name: material
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.footer
    - search.suggest
    - search.highlight
    - announce.dismiss
  plugins:
    - search
    - tags
    - offline
  extra:
    social:
      - icon: fontawesome/brands/mastodon 
        link: https://fosstodon.org/@test
      - icon: fontawesome/brands/github
        link: https://fosstodon.org/@test
      - icon: fontawesome/brands/linkedin
        link: https://fosstodon.org/@test
      - icon: fontawesome/brands/discord
        link: https://fosstodon.org/@test
  copyright: Copyright &copy; 2023 Hackernotebook.com