site_name: Hacker Notebook
site_url: https://hackernotebook.com
theme:
  name: material
  features:
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.prune
    - search.suggest
    - search.highlight
    - announce.dismiss
  plugins:
    - search
    - tags
    - offline